[uwsgi]
module = app:app
master = true
processes = 4
socket = /home/opc/flask_app/uwsgi.sock
chmod-socket = 666
touch-reload= /home/opc/flask_app/uwsgi.sock
vacuum = false
die-on-term = true
chdir = /home/opc/flask_app
